# Taller 1

- Jose Luis Tavera Ruiz (201821999)
- Aldemar Figueroa (202021091)


#### Librerias

In [3]:
import numpy as np
import time

#### Primer Punto

Para cualquier número 𝑛 > 1 se define la siguiente operación:

1. Si el número es par, se divide entre 2.
2. Si el número es impar, se multiplica por 3 y se suma 1.
3. Si es 1 termina.

Se define la secuencia de 𝒏 como la lista de resultados de cada operación hasta llegar
a 1. Por ejemplo, la secuencia de 6 es: 6, 3, 10, 5, 16, 8, 4, 2, 1. En este punto solo se
pueden utilizar las funcionalidades básicas de Python.

a. Cree una función que reciba un entero 𝑛 y retorne una lista con la secuencia de 𝑛.

In [23]:
def sequence(n):
    #Primero creamos una lista vacia donde guardaremos los valores de la secuencia
    sequence_list = []
    # Añadimos el primer valor de la secuencia a la lista
    sequence_list.append(n)

    #Mientras n sea distinto de 1, se ejecutara el siguiente bucle
    while n!=1:

        # Si n es par, se divide entre 2
        if n%2 == 0:   
            n= n/2

        # Si n es impar, se multiplica por 3 y se le suma 1
        else:
            n= (n*3) + 1
        
        # Se añade el valor de n a la lista
        sequence_list.append(n)

    return sequence_list

In [25]:
# Ahora haremos algunas pruebas para comprobar que la funcion sequence(n) funciona correctamente

print("Prueba con n=6")
sequence_list = sequence(6)
print(sequence_list)

print("")

print("Prueba con n=7")
sequence_list = sequence(7)
print(sequence_list)

Prueba con n=6
[6, 3.0, 10.0, 5.0, 16.0, 8.0, 4.0, 2.0, 1.0]

Prueba con n=7
[7, 22, 11.0, 34.0, 17.0, 52.0, 26.0, 13.0, 40.0, 20.0, 10.0, 5.0, 16.0, 8.0, 4.0, 2.0, 1.0]


b. Cree una función que reciba un entero 𝑚, retorne el valor 𝑛 tal que su secuencia
sea la más larga para los valores menores a 𝑚 y retorne el largo de la secuencia.
Utilice el punto a)

In [30]:
def longest_sequence(m):
    # Definimos n = 0 ya que toda secuencia tiene al menos un valor
    n=0
    # Definimos longest = 2 
    longest = 2
    
    # Hacemos un bucle que recorre todos los valores de la secuencia hasta m
    for i in range(2,m):
        
        # Calculamos la secuencia para cada valor de i
        sequence_i = sequence(i)
        # Calculamos la longitud de la secuencia
        length = len(sequence_i)
        
        # Si la longitud de la secuencia es mayor que n, actualizamos n y longest
        if length > n:
            longest = i
            n=length
    
    return ("Valor: " + str(longest), "Longitud: " + str(n))

print(longest_sequence(6))


('Valor: 3', 'Longitud: 8')


In [31]:
# Ahora haremos algunas pruebas para comprobar que la funcion longest_sequence(m) funciona correctamente
print("Prueba con n=6")
print(longest_sequence(6))

print("")

print("Prueba con n=7")
print(longest_sequence(6))


Prueba con n=6
('Valor: 3', 'Longitud: 8')

Prueba con n=7
('Valor: 3', 'Longitud: 8')


c. Similar al literal anterior, cree una función que reciba un entero 𝑚 y retorne un
diccionario donde las llaves sean enteros y los valores correspondan al largo de
las secuencias de cada entero.

In [22]:
def sequence_dictionary(m):   
    #Creamos un diccionario vacio donde guardaremos los valores de la secuencia
    all_lengths = {}

    #Hace un bucle que recorre todos los valores de la secuencia hasta m
    for i in range(2,m):
        
        # Calculamos la secuencia para cada valor de i
        sequence_i = sequence(i)
        # Calculamos la longitud de la secuencia
        length = len(sequence_i)
        # Guardamos la longitud de la secuencia en el diccionario
        all_lengths[i] = length 

    return all_lengths

resultado = sequence_dictionary(10)
print(resultado)

{2: 2, 3: 8, 4: 3, 5: 6, 6: 9, 7: 17, 8: 4, 9: 20}


d. Intenté modificar el punto a. y c. para crear una función que utiliza los resultados
calculados previamente y retorna un diccionario donde las llaves sean enteros y
los valores correspondan al largo de las secuencias de cada entero. Esto debería
permitirles crear una función mucho más rápida.

In [ ]:
def punto_1_d(m):
    dic = {}

    for i in range(2,m):
        secuencia_i = punto_1_a(i)
        longitud = len(secuencia_i)
        
        dic[i] = longitud 

    return dic

resultado = punto_1_d(6)
print(resultado)

e. Prueben las funciones del punto c. y d. con diferentes potencias de 10. 


#### Segundo Punto

En este punto solo se pueden utilizar las operaciones básicas de numpy. Los vectores
son arrays en numpy. Pueden asumir que los vectores 𝑌 solo toman dos valores.

a. Cree una función euclidean_distance que calcule la distancia euclidiana en $\mathbb{R}^n$ entre dos vectores $x$, $z$.

Para calcular la distancia euclidiana en $\mathbb{R}^n$ simplemente restamos los vectores componente a componente y elevamos al cuadrado. La raíz cuadrada de la suma de los cuadrados corresponde a la métrica euclidiana. Tomado de: [Stanford (1999)](https://hlab.stanford.edu/brian/euclidean_distance_in.html)

In [4]:
def euclidean_distance(x, z):
# Chequeamos si los vectores son del mismo tamaño
    if len(x) != len(z):
# En caso contrario, levantamos un error
        raise ValueError("The vectors must be the same size")
    else:
        return np.sqrt(np.sum((x - z)**2))

In [5]:
# Probamos la función con algunos ejemplos
x = np.array([1, 2, 3])
z = np.array([4, 5, 6])
print(x)
print(z)
print("Euclidean Distance: " + str(round(euclidean_distance(x, z), 4)))
print("")

x = np.array([1, 2, 3, 4, 5])
z = np.array([6, 7, 8, 9, 10])
print(x)
print(z)
print("Euclidean Distance: " + str(round(euclidean_distance(x, z), 4)))

[1 2 3]
[4 5 6]
Euclidean Distance: 5.1962

[1 2 3 4 5]
[ 6  7  8  9 10]
Euclidean Distance: 11.1803


b. Cree una función nearest_neighbor que, dado un vector 𝑥 y una matriz 𝑋_𝑡𝑟𝑎𝑖𝑛, retorna el vector de los datos de entrenamiento 𝑋_𝑡𝑟𝑎𝑖𝑛 que minimiza la distancia euclidiana a 𝑥. Debe utilizar la función euclidean_distance

In [6]:
def nearest_neighbor(x, X_train):
    # Definimos la distancia mínima como infinito
    min_distance = float('inf')
    # Definimos el vector más cercano como None
    nearest_vector = None
    
    # Iteramos sobre cada vector en el conjunto de entrenamiento
    for vector in X_train:
        # Calculamos la distancia entre el vector actual y el vector x
        distance = euclidean_distance(x, vector)
        # Si la distancia es menor que la distancia mínima actual
        if distance < min_distance:
            # Actualizamos la distancia mínima y el vector más cercano
            min_distance = distance
            nearest_vector = vector
    
    return nearest_vector

c. Cree una función k_nearest_neighbors que, dado un vector 𝑥, una
matriz 𝑋_𝑡𝑟𝑎𝑖𝑛 y un entero 𝑘, retorna los k vectores más cercanos de los datos
de entrenamiento 𝑋. Debe usar alguna de las funciones creadas previamente

In [10]:
def k_nearest_neighbors(x, X_train, k):
    # Creamos un diccionario para guardar las distancias y los vectores
    distances_dict = {}
    # Creamos una lista para guardar todas las distancias
    all_distances = []
    # Iteramos sobre cada vector en el conjunto de entrenamiento
    for vector in X_train:
        # Calculamos la distancia entre el vector actual y el vector x
        distance = euclidean_distance(x, vector)
        # Guardamos la distancia en la lista
        all_distances.append(distance)
        # GUarda la distancia y el vector en el diccionario
        distances_dict[distance] = vector
    
    # Sorteamos todas las distancias
    all_distances.sort()
    # Guardamos los k vectores más cercanos
    k_nearest = [distances_dict[distance] for distance in all_distances[:k]]
    
    return k_nearest

In [11]:
# Ejemplo de uso:
x = np.array([1, 2, 3])
X_train = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12], [0, 0, 0]])
k = 2

nearest = k_nearest_neighbors(x, X_train, k)
print(f"Los {k} vectores más cercanos en X_train a x son:", nearest)

Los 2 vectores más cercanos en X_train a x son: [array([0, 0, 0]), array([4, 5, 6])]


d. Cree una función predict_class que, dado vector 𝑥, una matriz 𝑋_𝑡𝑟𝑎𝑖𝑛, un
vector 𝑌_𝑡𝑟𝑎𝑖𝑛, y un entero 𝑘, haga la predicción de cuál debe ser su clase
(binaria) según el algoritmo de kNN. Debe utilizar la función
k_nearest_neighbors.