# Taller 1

- Jose Luis Tavera Ruiz (201821999)
- Aldemar Figueroa (202021091)


### Librerias

In [1]:
import numpy as np

2. En este punto solo se pueden utilizar las operaciones básicas de numpy. Los vectores
son arrays en numpy. Pueden asumir que los vectores 𝑌 solo toman dos valores.

a. Cree una función euclidean_distance que calcule la distancia euclidiana en $\mathbb{R}^n$ entre dos vectores $x$, $z$.

Para calcular la distancia euclidiana en $\mathbb{R}^n$ simplemente restamos los vectores componente a componente y elevamos al cuadrado. La raíz cuadrada de la suma de los cuadrados corresponde a la métrica euclidiana. Tomado de: [Stanford (1999)](https://hlab.stanford.edu/brian/euclidean_distance_in.html)

In [3]:
def euclidean_distance(x, z):
# Chequeamos si los vectores son del mismo tamaño
    if len(x) != len(z):
# En caso contrario, levantamos un error
        raise ValueError("The vectors must be the same size")
    else:
        return np.sqrt(np.sum((x - z)**2))

In [12]:
# Probamos la función con algunos ejemplos
x = np.array([1, 2, 3])
z = np.array([4, 5, 6])
print(x)
print(z)
print("Euclidean Distance: " + str(round(euclidean_distance(x, z), 4)))
print("")

x = np.array([1, 2, 3, 4, 5])
z = np.array([6, 7, 8, 9, 10])
print(x)
print(z)
print("Euclidean Distance: " + str(round(euclidean_distance(x, z), 4)))

[1 2 3]
[4 5 6]
Euclidean Distance: 5.1962

[1 2 3 4 5]
[ 6  7  8  9 10]
Euclidean Distance: 11.1803


b. Cree una función nearest_neighbor que, dado un vector 𝑥 y una matriz 𝑋_𝑡𝑟𝑎𝑖𝑛, retorna el vector de los datos de entrenamiento 𝑋_𝑡𝑟𝑎𝑖𝑛 que minimiza la distancia euclidiana a 𝑥. Debe utilizar la función euclidean_distance

In [13]:
def nearest_neighbor(x, X_train):
    # Definimos la distancia mínima como infinito
    min_distance = float('inf')
    # Definimos el vector más cercano como None
    nearest_vector = None
    
    # Iteramos sobre cada vector en el conjunto de entrenamiento
    for vector in X_train:
        # Calculamos la distancia entre el vector actual y el vector x
        distance = euclidean_distance(x, vector)
        # Si la distancia es menor que la distancia mínima actual
        if distance < min_distance:
            # Actualizamos la distancia mínima y el vector más cercano
            min_distance = distance
            nearest_vector = vector
    
    return nearest_vector

c. Cree una función k_nearest_neighbors que, dado un vector 𝑥, una
matriz 𝑋_𝑡𝑟𝑎𝑖𝑛 y un entero 𝑘, retorna los k vectores más cercanos de los datos
de entrenamiento 𝑋. Debe usar alguna de las funciones creadas previamente

In [15]:
def k_nearest_neighbors(x, X_train, k):
    # Creamos un diccionario para guardar las distancias y los vectores
    distances_dict = {}
    # Creamos una lista para guardar todas las distancias
    all_distances = []
    # Iteramos sobre cada vector en el conjunto de entrenamiento
    for vector in X_train:
        # Calculamos la distancia entre el vector actual y el vector x
        distance = euclidean_distance(x, vector)
        # Guardamos la distancia en la lista
        all_distances.append(distance)
        # GUarda la distancia y el vector en el diccionario
        distances_dict[distance] = vector
    
    # Sorteamos todas las distancias
    all_distances.sort()
    # Guardamos los k vectores más cercanos
    k_nearest = [distances_dict[distance] for distance in all_distances[:k]]
    
    return k_nearest

In [17]:
# Ejemplo de uso:
x = np.array([1, 2, 3])
X_train = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12], [0, 0, 0]])
k = 2

nearest = k_nearest_neighbors(x, X_train, k)
print(f"Los {k} vectores más cercanos en X_train a x son:", nearest)

Los 2 vectores más cercanos en X_train a x son: [array([0, 0, 0]), array([4, 5, 6])]


d. Cree una función predict_class que, dado vector 𝑥, una matriz 𝑋_𝑡𝑟𝑎𝑖𝑛, un
vector 𝑌_𝑡𝑟𝑎𝑖𝑛, y un entero 𝑘, haga la predicción de cuál debe ser su clase
(binaria) según el algoritmo de kNN. Debe utilizar la función
k_nearest_neighbors.